"""Публикация payload оркестратора как draft PR (шаг 4).

Вызывается из ноды publish при DOCAGENT_PUBLISH_TARGET=github.
Контракт: state["payload"] = {branch, commit_message, body_md, files:[{path, content_md, ...}]}
Идемпотентность: повторный запуск того же thread обновляет существующий PR
(заголовок ветки docagent/<thread>), не создаёт дублей.
"""
from __future__ import annotations

import re

from ..config import Settings
from .client import GitHubClient


def _repo_slug(payload: dict, s: Settings) -> str:
    pr_ref = payload.get("pr_ref", "")
    m = re.search(r"github\.com/([\w.-]+/[\w.-]+)", pr_ref)
    if m:
        return m.group(1)
    # "owner/name#7" или "owner/name/pulls/7" — но не локальный путь к .diff
    if not pr_ref.endswith(".diff") and "/" in pr_ref:
        return pr_ref.split("/pulls")[0].split("#")[0]
    return s.demo_repo


def render_doc_file(existing: str | None, file: dict) -> str:
    """Вставляет/заменяет черновик в целевом md-файле по anchor.

    MVP-стратегия: append под якорным заголовком; если файла нет — создаём
    скелет с front-matter 'generated by DocAgent'.
    """
    content = file["content_md"].strip() + "\n"
    heading = f"## DocAgent · {file['target']}"
    block = f"{heading}\n\n{content}"
    if not existing:
        return (f"# {file['target'].replace('-', ' ').title()}\n\n"
                "_Сгенерировано DocAgent (черновик, до одобрения team lead)._ \n\n"
                + block + "\n")
    # замена предыдущего блока этого target, иначе append
    pat = re.compile(re.escape(heading) + r"\b.*?(?=\n## |\Z)", re.S)
    if pat.search(existing):
        return pat.sub(block, existing)
    return existing.rstrip() + "\n\n" + block + "\n"


def publish_to_github(state: dict, s: Settings, client: GitHubClient | None = None) -> dict:
    """Создаёт/обновляет draft PR. Возвращает delta для OrchState."""
    c = client or GitHubClient(settings=s)
    payload = state.get("payload", {})
    slug = _repo_slug(payload, s)
    tid = re.sub(r"[^A-Za-z0-9_.-]", "_", state.get("thread_id", "run"))
    branch = f"{s.bot_branch_prefix}{tid}"

    files_out = []
    for f in payload.get("files", []):
        existing = None
        try:
            existing = c.repo(slug).get_content(f["path"]).decoded_content.decode()
        except Exception:
            pass  # файла нет — создадим
        files_out.append({"path": f["path"],
                          "content": render_doc_file(existing, f)})

    base_sha = c.repo(slug).get_branch("main").commit.sha
    c.create_blob_commit(slug, branch, base_sha, files_out,
                         payload.get("commit_message", "docs: auto"))
    title = f"Docs: {payload.get('pr_ref', tid)}"
    body = payload.get("body_md", "")
    if payload.get("needs_human_edit"):
        body += "\n\nneeds_human_edit\n"
    res = c.open_draft_pr(slug, branch, title, body)
    return {"pr_number": res["number"], "pr_url": res["html_url"],
            "publish_mode": "github"}
