"""Публикация payload оркестратора как draft PR (шаг 4).

Вызывается из ноды publish при DOCAGENT_PUBLISH_TARGET=github.
Контракт: state["payload"] = {branch, commit_message, body_md, files:[{path, content_md, ...}]}
Идемпотентность: повторный запуск того же thread обновляет существующий PR
(заголовок ветки docagent/<thread>), не создаёт дублей.
"""
from __future__ import annotations

import re

from ..config import Settings
from .client import GitHubClient


def _repo_slug(payload: dict, s: Settings) -> str:
    pr_ref = payload.get("pr_ref", "")
    m = re.search(r"github\.com/([\w.-]+/[\w.-]+)", pr_ref)
    if m:
        return m.group(1)
    # "owner/name#7" или "owner/name/pulls/7" — но не локальный путь к .diff
    if not pr_ref.endswith(".diff") and "/" in pr_ref \
            and not pr_ref.startswith(("/", "\\")) \
            and ":" not in pr_ref.split("/")[0]:  # "F:\\..." это путь, не slug
        return pr_ref.split("/pulls")[0].split("#")[0]
    return s.demo_repo


def render_doc_file(existing: str | None, file: dict) -> str:
    """Вставляет/заменяет черновик в целевом md-файле по anchor.

    MVP-стратегия: append под якорным заголовком; если файла нет — создаём
    скелет с front-matter 'generated by DocAgent'.
    """
    content = file["content_md"].strip() + "\n"
    heading = f"## DocAgent · {file['target']}"
    block = f"{heading}\n\n{content}"
    if not existing:
        return (f"# {file['target'].replace('-', ' ').title()}\n\n"
                "_Сгенерировано DocAgent (черновик, до одобрения team lead)._ \n\n"
                + block + "\n")
    # замена предыдущего блока этого target, иначе append
    pat = re.compile(re.escape(heading) + r"\b.*?(?=\n## |\Z)", re.S)
    if pat.search(existing):
        return pat.sub(block, existing)
    return existing.rstrip() + "\n\n" + block + "\n"


def publish_to_github(state: dict, s: Settings, client: GitHubClient | None = None) -> dict:
    """Создаёт/обновляет draft PR. Возвращает delta для OrchState."""
    c = client or GitHubClient(settings=s)
    payload = state.get("payload", {})
    slug = _repo_slug(payload, s)
    tid = re.sub(r"[^A-Za-z0-9_.-]", "_", state.get("thread_id", "run"))
    branch = f"{s.bot_branch_prefix}{tid}"

    repo_obj = c.repo(slug)
    branch_ref_sha = None
    try:  # существующая ветка этого же треда => ОБНОВЛЕНИЕ PR, а не новый PR
        branch_ref_sha = repo_obj.get_git_ref(f"heads/{branch}").object.sha
    except Exception:
        pass

    files_out = []
    for f in payload.get("files", []):
        existing = None
        # при апдейте сравниваем с версией на НАШЕЙ ветке (её уже мержили в
        # main? нет; но предыдущий пуш именно туда), иначе — с base
        cmp_ref = {"ref": branch_ref_sha} if branch_ref_sha else {}
        try:
            existing = repo_obj.get_contents(f["path"], **cmp_ref).decoded_content.decode()
        except Exception:
            try:
                existing = repo_obj.get_contents(f["path"]).decoded_content.decode()
            except Exception:
                pass  # файла нет нигде — создадим
        new_content = render_doc_file(existing, f)
        if existing is not None and new_content == existing:
            continue  # контент идентичен текущему состоянию цели коммита
        files_out.append({"path": f["path"], "content": new_content})

    if not files_out:
        raise RuntimeError(
            f"publish skipped: nothing to commit on top of {'branch ' + branch_ref_sha[:8] if branch_ref_sha else 'main'} "
            f"in {slug} (thread={tid}). GitHub отклонил бы такой PR ошибкой "
            "'No commits between main and <branch>'. Причины: 1) файлы docs/ из "
            "предыдущего draft PR'а были смержены в main руками; 2) бот уже "
            "публиковал идентичный черновик. Исправление: закройте старый PR и "
            "удалите ветку docagent/<thread>, либо откатите docs/ из main.")

    # parent коммита: если ветка уже существует (ревью-правки / повторный пуск) —
    # поверх её HEAD (получаем непустой diff и апдейт того же PR); иначе — main.
    parent_sha = branch_ref_sha or repo_obj.get_branch("main").commit.sha
    c.create_blob_commit(slug, branch, parent_sha, files_out,
                         payload.get("commit_message", "docs: auto"))
    title = f"Docs: {payload.get('pr_ref', tid)}"
    body = payload.get("body_md", "")
    if payload.get("needs_human_edit"):
        body += "\n\nneeds_human_edit\n"

    def _update_existing() -> dict | None:
        """Ветка живёт => draft PR по ней почти наверняка уже открыт (наш).
        GitHub не даёт два PR на одну пару head/base (422 'A pull request
        already exists for ...'), поэтому сначала апдейт, только если PR нет —
        создаём новый."""
        try:
            prs = list(repo_obj.get_pulls(state="open",
                                          head=f"{slug.split('/')[0]}:{branch}"))
        except Exception:
            prs = []
        if not prs:
            return None
        pr = prs[0]
        try:
            pr.edit(title=title, body=body)
        except Exception:
            pass  # тело/заголовок вторичны, коммит уже запушен
        return {"pr_number": pr.number, "pr_url": pr.html_url,
                "publish_mode": "github", "updated": True}

    if branch_ref_sha:
        upd = _update_existing()
        if upd:
            return upd

    try:
        res = c.open_draft_pr(slug, branch, title, body)
    except Exception as e:
        # гонка/легаси-PR в closed: пробуем ещё раз найти и обновить
        upd = _update_existing()
        if upd:
            return upd
        raise RuntimeError(
            f"open_draft_pr failed for {slug} ({branch} -> main): {e}. "
            "Если это 'pull request already exists' — закрой старый PR или "
            "удали ветку docagent/<thread> и повтори.") from e
    return {"pr_number": res["number"], "pr_url": res["html_url"],
            "publish_mode": "github"}
